version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: codemonkey076/laravel-php-redis
    container_name: php
    hostname: laravel
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./profile:/root
    ports:
      - 9000:9000
    networks:
      - laravel

  horizon:
    image: codemonkey076/laravel-php-redis
    container_name: horizon
    restart: always
    command: php /var/www/artisan horizon
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  websockets:
    image: codemonkey076/laravel-php-redis
    container_name: websockets
    restart: always
    command: php /var/www/artisan websockets:serve
    ports:
      - 6001:6001
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - laravel
    depends_on:
      - mysql
